[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "dynamic_default_args",
    "numpy",
    "sympy",
]

[tool.cibuildwheel]
build = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "cp310-*"]
