__all__ = [
    'VERSION_MAJOR',
    'VERSION_MINOR',
    'VERSION_PATCH',
    'VERSION_STRING',
    '__version__',
]

VERSION_MAJOR = 0
VERSION_MINOR = 2
VERSION_PATCH = 0

VERSION_STRING = f'{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}'

__version__ = VERSION_STRING
